name: coast
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip>=22.2.2
  - cartopy>=0.21.0
  - gsw==3.4.0
  - pip:
    - numpy==1.22.3
    - dask>=2022.3.0
    - dask[complete]>=2022.3.0
    - xarray>=2022.3.0
    - matplotlib>=3.5.3
    - netCDF4==1.5.8
    - scipy>=1.8.0
    - gsw==3.4.0
    - utide>=0.3.0
    - scikit-learn>=1.0.2
    - tqdm>=4.66.1
    - pyproj>=3.5.0
    - scikit-image>=0.19.2
    - statsmodels>=0.13.2
    - pydap>=3.2.2
    - lxml>=4.9.0
    - requests>=2.27.1
    - spyder>=5.1.5
    - jupyterlab
