name: coast
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - cython
  - cartopy>=0.21.0
  - gsw>=3.6.17
  - xarray>=2022.3.0
  - h5py
  - netCDF4==1.5.8
  - zarr
  - pip
  - pytest==7.1.1
  - pytest-mock==3.7.0
  - numpy==1.26.4
  - dask>=2022.3.0
  - dask[complete]>=2022.3.0
  - matplotlib>=3.5.3
  - scipy>=1.8.0
  - utide>=0.3.0
  - scikit-learn>=1.0.2
  - tqdm>=4.66.1
  - pyproj>=3.5.0
  - scikit-image>=0.19.2
  - statsmodels>=0.13.2
  - pydap>=3.2.2
  - lxml>=4.9.0
  - requests>=2.27.1
  - spyder>=5.1.5
  - jupyterlab