about:
  dev_url: ''
  doc_url: ''
  home: https://www.bodc.ac.uk
  license: Put something here
  license_family: OTHER
  license_file: ''
  summary: This is the Coast Ocean Assessment Tool
build:
  number: 0
  script: pip install https://files.pythonhosted.org/packages/83/cc/c62100906d30f95d46451c15eb407da7db201e30f42008f3643945910373/graphviz-0.14-py2.py3-none-any.whl
extra:
  recipe-maintainers:
  - British-Oceanographic-Data-Centre
package:
  name: coast
  version: 0.2.1a19
requirements:
  host:
  - dask[complete]
  - xarray
  - numpy
  - matplotlib
  - netCDF4
  run:
  - dask[complete]
  - xarray
  - numpy
  - matplotlib
  - netCDF4
source:
  url: https://pypi.io/packages/source/C/COAsT/COAsT-0.2.1a19.tar.gz
test:
  imports:
  - coast
