name: notebook_to_md (general)
on: pull_request
jobs:
  commit-notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout site
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch Hugo themes and all extra projects
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          path: site

      - name: Checkout coast
        uses: actions/checkout@v4
        with:
          repository: British-Oceanographic-Data-Centre/COAsT
          ref: bug/kernel_died_notebook
          path: external

      - name: Prepare environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: coast
          environment-file: external/environment.yml
      - name: prep exec notebooks
        run: |
          conda info
          conda list
          conda config --show
          cd $GITHUB_WORKSPACE/external
          sudo apt install wget unzip -y
          wget -q https://linkedsystems.uk/erddap/files/COAsT_example_files/COAsT_example_files.zip
          unzip COAsT_example_files.zip && mv COAsT_example_files ./example_scripts/notebook_tutorials/runnable_notebooks/general/example_files          
          mkdir -p ./example_scripts/notebook_tutorials/markdown/general
          ls ./example_scripts/notebook_tutorials
          pip install .
          sudo apt-get update
          sudo apt-get install -y libgeos-dev
          pip install cartopy==0.21.0
          pip install zarr
          pip install jupyter notebook jupyter-contrib-core==0.4.0 jupyter-contrib-nbextensions==0.5.1 jupyter-highlight-selected-word==0.2.0 jupyter-latex-envs==1.4.6 jupyter-nbextensions-configurator==0.5.0 jupyter-resource-usage==0.6.3 jupyter-server==1.21.0 jupyter_client==7.4.3 jupyter_core==4.11.2 jupyterlab==3.4.8 jupyterlab-pygments==0.2.2 jupyterlab-widgets==1.1.1 jupyterlab_server==2.16.1
          mv config ./example_scripts/notebook_tutorials/runnable_notebooks/general/config
          bash notebook_to_md.sh general
