name: push_notebooks

on:
  push:
    branches: develop
    paths:
      - example_scripts/notebooks/**
jobs:
  push-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: British-Oceanographic-Data-Centre/COAsT-site
          event-type: push-notebook
          client-payload: '{"deploy_notebook":true}'
